/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textpad;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author dell
 */
public class Textpad extends javax.swing.JFrame implements DocumentListener {

    /**
     * Creates new form Textpad
     */
    File file;
    boolean status=false;
    JFileChooser fc;
    Image image;
    public Textpad() {
        initComponents();
        fc = new JFileChooser("e:/");
        image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("Notepad.png"));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setIconImage(image);
        jTextArea1.getDocument().addDocumentListener(this);
    }
    
    private void SaveWithName()
    {
            int x=fc.showSaveDialog(this);
            if(x==JFileChooser.APPROVE_OPTION)
            {
                file=fc.getSelectedFile();
                try(FileWriter writer=new FileWriter(file);)
                {
                    char[] data=jTextArea1.getText().toCharArray();
                    writer.write(data);
                }
                catch(Exception ex)
                {
                
                }
                this.setTitle(file.getAbsolutePath()+" - TextPad");
            }
    }
    
    private void SaveWithoutName()
    {
                try(FileWriter writer=new FileWriter(file);)
                {
                    char[] data=jTextArea1.getText().toCharArray();
                    writer.write(data);
                }
                catch(Exception ex)
                {
                
                }
                this.setTitle(file.getAbsolutePath()+" - TextPad");
    }
    
    private void checkStatus()
    {
        if(status)
        {
            int x=JOptionPane.showConfirmDialog(this, "Do you want to  save changes ?", "TextPad", JOptionPane.YES_NO_OPTION);
            if(x==JOptionPane.YES_OPTION)
            {
                if(file==null)
                {
                    SaveWithName();
                }
                else
                {
                    SaveWithoutName();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        newbtn = new javax.swing.JButton();
        openbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        copybtn = new javax.swing.JButton();
        cutbtn = new javax.swing.JButton();
        pastebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TEXTPAD");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        newbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/New_32x32.png"))); // NOI18N
        newbtn.setToolTipText("New File");
        newbtn.setFocusable(false);
        newbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(newbtn);

        openbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/Open_32x32.png"))); // NOI18N
        openbtn.setToolTipText("Open File");
        openbtn.setFocusable(false);
        openbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(openbtn);

        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/Save_32x32.png"))); // NOI18N
        savebtn.setToolTipText("Save File");
        savebtn.setFocusable(false);
        savebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        savebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(savebtn);

        copybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/Copy_32x32.png"))); // NOI18N
        copybtn.setToolTipText("Copy");
        copybtn.setFocusable(false);
        copybtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copybtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        copybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copybtnActionPerformed(evt);
            }
        });
        jToolBar1.add(copybtn);

        cutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/Cut_32x32.png"))); // NOI18N
        cutbtn.setToolTipText("Cut");
        cutbtn.setFocusable(false);
        cutbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(cutbtn);

        pastebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textpad/Paste_32x32.png"))); // NOI18N
        pastebtn.setToolTipText("Paste");
        pastebtn.setFocusable(false);
        pastebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pastebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pastebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(pastebtn);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Save As");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Copy");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Cut");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Paste");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openbtnActionPerformed
            checkStatus();
            int x=fc.showOpenDialog(this);
            if(x==JFileChooser.APPROVE_OPTION)
            {
                file=fc.getSelectedFile();
                try(FileReader reader=new FileReader(file);)
                {
                    char[] data=new char[(int)file.length()];
                    reader.read(data);
                    jTextArea1.setText(new String(data));
                }
                catch(Exception ex)
                {
                
                }
                this.setTitle(file.getAbsolutePath()+" - TextPad");
                status=false;
            }        // TODO add your handling code here:
    }//GEN-LAST:event_openbtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            checkStatus();
            file=null;
            jTextArea1.setText(null);
            this.setTitle("TextPad");
            status=false;            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            checkStatus();
            int x=fc.showOpenDialog(this);
            if(x==JFileChooser.APPROVE_OPTION)
            {
                file=fc.getSelectedFile();
                try(FileReader reader=new FileReader(file);)
                {
                    char[] data=new char[(int)file.length()];
                    reader.read(data);
                    jTextArea1.setText(new String(data));
                }
                catch(Exception ex)
                {
                
                }
                this.setTitle(file.getAbsolutePath()+" - TextPad");
                status=false;
            }// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
                if(file==null)
                {
                    SaveWithName();
                }
                else
                {
                    SaveWithoutName();
                }
                status=false;// TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void copybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copybtnActionPerformed
            jTextArea1.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_copybtnActionPerformed

    private void cutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutbtnActionPerformed
            jTextArea1.cut();        // TODO add your handling code here:
    }//GEN-LAST:event_cutbtnActionPerformed

    private void pastebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastebtnActionPerformed
            jTextArea1.paste();        // TODO add your handling code here:
    }//GEN-LAST:event_pastebtnActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
            jTextArea1.copy();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
            jTextArea1.cut();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
            jTextArea1.paste();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
                if(file==null)
                {
                    SaveWithName();
                }
                else
                {
                    SaveWithoutName();
                }
                status=false;// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
                SaveWithoutName();
                status=false;// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void newbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbtnActionPerformed
            checkStatus();
            file=null;
            jTextArea1.setText(null);
            this.setTitle("TextPad");
            status=false;// TODO add your handling code here:
    }//GEN-LAST:event_newbtnActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            checkStatus();
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            checkStatus();
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
            JOptionPane.showMessageDialog(this, "TextPad is the simple text editor for windows.\nIt is a general purpose editor for plain text files.\nEasy to use with all the features a basic notepad or text editor requires.","About",1);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Textpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Textpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Textpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Textpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Textpad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copybtn;
    private javax.swing.JButton cutbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newbtn;
    private javax.swing.JButton openbtn;
    private javax.swing.JButton pastebtn;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        jLabel1.setText("Total Characters : "+jTextArea1.getText().length());
        status=true;
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        jLabel1.setText("Total Characters : "+jTextArea1.getText().length());
        status=true;
    }

    @Override
    public void changedUpdate(DocumentEvent e) {

    }
}
